[package]
name = "atmosphere"
version = "0.1.0"
authors = ["Zhaofeng Li <hello@zhaofeng.li>"]
edition = "2018"
build = "build.rs"

[dependencies]
astd = { path = "../astd" }

bit_field = "0.10.1"
log = "0.4.14"
multiboot = "0.7.0"
num-derive = "0.3.3"
x86 = "0.39.0"

[dependencies.snafu]
version = "0.6.10"
default-features = false

[dependencies.num]
version = "0.4"
default-features = false

[build-dependencies]
nasm-rs = "0.1.5"
