name: EditorConfig Check

on:
  pull_request:
  push:
jobs:
  build:
    # Modify this to "ubuntu-latest" for GitHub-hosted runners
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2.3.4

      - uses: cachix/install-nix-action@v13
        with:
          install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.4pre20210604_8e6ee1b/install
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Enable binary cache (optional)
        uses: cachix/cachix-action@v10
        continue-on-error: true
        with:
          name: mars-research

      - run: nix-shell --run "editorconfig-checker"
