name: Linters

on:
  pull_request:
  push:
jobs:
  linters:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.2

      - uses: cachix/install-nix-action@v17
        with:
          install_url: https://releases.nixos.org/nix/nix-2.11.1/install
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Enable binary cache (optional)
        uses: cachix/cachix-action@v10
        continue-on-error: true
        with:
          name: mars-research

      - name: Check EditorConfig
        run: nix-shell --run "editorconfig-checker"

      - name: Check rustfmt
        run: nix-shell --run "cargo fmt --check"
